/* eslint-disable */
//  WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// test
const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:38378b8c-d784-4335-8f3f-e86c4831ab61",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_8Uwj1GUOv",
    "aws_user_pools_web_client_id": "4ts5ifotatafe8238j5mvpmch3",
    "oauth": {}
};


export default awsmobile;
